accounts/urls.py
from django.urls import path
from .views import MyProfile
from django.contrib.auth import views as auth_views
from .views import (
    LogInView, ResendActivationCodeView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView
)
from django.conf.urls.i18n import i18n_patterns



app_name = 'accounts'


urlpatterns = [
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    #
    # path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),
    #
    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),
    #
    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),
    #
    #
    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
    path('<int:pk>', MyProfile.as_view(), name='myprofile'),
    # path('profileupdate/<int:pk>', MyProfileUpdate.as_view(), name='profileupdate'),
    # path('users/', AllUsersList.as_view(), name='users'),
    # path('create/', CreateUser.as_view(), name='create'),
    # path('delete/<int:pk>', DeleteUser.as_view(), name='delete'),
    # path('detail/<int:pk>', DetailUser.as_view(), name='detail'),
    # path('update/<int:pk>', UserUpdate.as_view(), name='update'),
    # path('mygrouplist/', MyGroupList.as_view(), name='mygrouplist'),
]

api/urls.py
from api.views.accounts import AccountViewSet
from api.views.invites import InviteViewSet, InviteRegistrationViewSet
from api.views.projects import ProjectViewSet

from rest_framework.routers import DefaultRouter
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views.accounts import account_registration_handler

router = DefaultRouter()
router.register('user', AccountViewSet)
router.register('invite', InviteViewSet)
router.register('invite_reg', InviteRegistrationViewSet)
router.register('project', ProjectViewSet)

jwturlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns = [
   path('register_user', account_registration_handler),
] + router.urls  + jwturlpatterns

backend/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import index_page, about_page, home_page, projects_list


from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('accounts/', include("accounts.urls")),
    path('about/', about_page, name="about"),
    path('', home_page, name="home"),
    path('projects/', projects_list, name="projects-list"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

args = tuple(urlpatterns)
urlpatterns = i18n_patterns(*args)

accounts/views.py
from django.contrib.auth import login, authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth import login as auth_logout
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LogoutView as BaseLogoutView, PasswordChangeView as BasePasswordChangeView,
    PasswordResetDoneView as BasePasswordResetDoneView, PasswordResetConfirmView as BasePasswordResetConfirmView,
)
from django.shortcuts import get_object_or_404, redirect
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy, reverse
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView, DetailView, ListView, UpdateView, CreateView, DeleteView
from django.conf import settings

from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from .utils import (
    send_activation_email, send_reset_password_email, send_forgotten_username_email, send_activation_change_email,
)
from .forms import (
    SignInViaEmailForm, SignUpForm,
    RestorePasswordForm, RestorePasswordViaEmailOrUsernameForm, RemindUsernameForm,
    ResendActivationCodeForm, ResendActivationCodeViaEmailForm, ChangeProfileForm, ChangeEmailForm, UpdateUserForm
)
from .models import Account, Activation
from .forms import ProfileForm, CreateForm
from invite.models import InviteRegistration
from api.views.accounts import create_invite_registration, check_invite_not_empty, is_check_invite_exists
from api.serializers.accounts import AccountRegistrationSerializer


class GuestOnlyView(View):
    def dispatch(self, request, *args, **kwargs):
        # Redirect to the index page if the user already authenticated
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)

        return super().dispatch(request, *args, **kwargs)


class LogInView(GuestOnlyView, FormView):
    template_name = 'accounts/login.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.LOGIN_VIA_EMAIL:
            return SignInViaEmailForm

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        request = self.request

        # If the test cookie worked, go ahead and delete it since its no longer needed
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()

        # The default Django's "remember me" lifetime is 2 weeks and can be changed by modifying
        # the SESSION_COOKIE_AGE settings' option.
        if settings.USE_REMEMBER_ME:
            if not form.cleaned_data['remember_me']:
                request.session.set_expiry(0)

        login(request, form.user_cache)

        redirect_to = request.POST.get(REDIRECT_FIELD_NAME, request.GET.get(REDIRECT_FIELD_NAME))
        url_is_safe = is_safe_url(redirect_to, allowed_hosts=request.get_host(), require_https=request.is_secure())

        if url_is_safe:
            return redirect(redirect_to)

        return redirect(settings.LOGIN_REDIRECT_URL)


class SignUpView(GuestOnlyView, FormView):
    template_name = 'accounts/signin.html'
    form_class = SignUpForm

    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)

        if settings.DISABLE_USERNAME:
            # Set a temporary username
            user.username = get_random_string()
        else:
            user.username = form.cleaned_data['username']

        if settings.ENABLE_USER_ACTIVATION:
            user.is_active = False

        invite = request.POST['invite']

        if is_check_invite_exists(invite):
            if check_invite_not_empty(invite):

                # Create a user record
                user.save()
                create_invite_registration(invite, user)

                if settings.ENABLE_USER_ACTIVATION:
                    code = get_random_string(20)

                    act = Activation()
                    act.code = code
                    act.user = user
                    act.save()

                    send_activation_email(request, user.email, code)

                    messages.success(
                        request, _('You are signed up. To activate the account, follow the link sent to the mail.'))
                else:
                    raw_password = form.cleaned_data['password1']

                    user = authenticate(username=user.username, password=raw_password)
                    login(request, user)

                    messages.success(request, _('You are successfully signed up!'))

                    # Change the username to the "user_ID" form
                    if settings.DISABLE_USERNAME:
                        user.username = f'user_{user.id}'
                        user.save()

                    return redirect('accounts/login')
            else:
                messages.success(
                    request, _('Invite empty.'))

        else:
            messages.success(
                request, _('This invite dose note exists.'))

        return redirect('/')


class ActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Activate profile
        user = act.user
        user.is_active = True
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully activated your account!'))

        return redirect('accounts:login')


class ResendActivationCodeView(GuestOnlyView, FormView):
    template_name = 'accounts/resend_activation_code.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME:
            return ResendActivationCodeViaEmailForm

        return ResendActivationCodeForm

    def form_valid(self, form):
        user = form.user_cache

        activation = user.activation_set.first()
        activation.delete()

        code = get_random_string(20)

        act = InviteRegistration()
        # act.code = code
        # act.user = user
        act.save()

        send_activation_email(self.request, user.email, code)

        messages.success(self.request, _('A new activation code has been sent to your email address.'))

        return redirect('accounts:resend_activation_code')


class RestorePasswordView(GuestOnlyView, FormView):
    template_name = 'accounts/restore_password.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.RESTORE_PASSWORD_VIA_EMAIL_OR_USERNAME:
            return RestorePasswordViaEmailOrUsernameForm

        return RestorePasswordForm

    def form_valid(self, form):
        user = form.user_cache
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk)).decode()

        send_reset_password_email(self.request, user.email, token, uid)

        return redirect('accounts:restore_password_done')


class ChangeProfileView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_profile.html'
    form_class = ChangeProfileForm

    def get_initial(self):
        user = self.request.user
        initial = super().get_initial()
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        return initial

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()

        messages.success(self.request, _('Profile data has been successfully updated.'))

        return redirect('accounts:change_profile')


class ChangeEmailView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_email.html'
    form_class = ChangeEmailForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial['email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        user = self.request.user
        email = form.cleaned_data['email']

        if settings.ENABLE_ACTIVATION_AFTER_EMAIL_CHANGE:
            code = get_random_string(20)

            act = InviteRegistration()
            # act.code = code
            # act.user = user
            # act.email = email
            act.save()

            send_activation_change_email(self.request, email, code)

            messages.success(self.request, _('To complete the change of email address, click on the link sent to it.'))
        else:
            user.email = email
            user.save()

            messages.success(self.request, _('Email successfully changed.'))

        return redirect('accounts:change_email')


class ChangeEmailActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(InviteRegistration, code=code)

        # Change the email
        user = act.user
        user.email = act.email
        user.save()

        # Remove the activation record
        act.delete()

api/views/accounts.py
from accounts.models import Account
from invite.models import Invite, InviteRegistration
from api.serializers.accounts import AccountSerializer

from rest_framework.viewsets import ModelViewSet
from rest_framework.pagination import PageNumberPagination

from django.http import HttpResponse
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from api.serializers.accounts import AccountRegistrationSerializer


class LargeResultsSetPagination(PageNumberPagination):
    page_size = 5


class AccountViewSet(ModelViewSet):
    serializer_class = AccountSerializer
    queryset = Account.objects.all()
    pagination_class = LargeResultsSetPagination


def check_invite_not_empty(invite):
    invite_obj = Invite.objects.get(uuid=invite)

    if invite_obj.capacity > 0 and invite_obj.remaining_volume <= invite_obj.capacity:
        if invite_obj.remaining_volume > 0:
            invite_obj.remaining_volume -= 1
            invite_obj.save()
            print('Minus odna registraciya')
            return True
        else:
            return False
    else:
        return False


def is_check_invite_exists(invite):
    try:
        Invite.objects.get(uuid=invite)
        return True
    except Exception:
        return False


def create_user(email, password, invite):
    try:
        Account.objects.get(email=email)
        return HttpResponse('Uzver this email exist', 403)
    except Exception:
        user_id = Account.objects.create_user(email, password)
        user_id.is_active = False
        user_id.save()
        print(user_id.email + " " + str(user_id.id))

        create_invite_registration(invite, user_id)

    return user_id.id


def create_invite_registration(invite, user_id):
    invite_obj = Invite.objects.get(uuid=invite)
    inv_reg_obj = InviteRegistration.objects.create(invite=invite_obj, account=user_id)
    inv_reg_obj.save()
    print(f'User {user_id.email} with invite - {invite} was registered: {inv_reg_obj.id}')
    user_id.is_active = True
    user_id.save()
    print(f'User {user_id.email} - ACITVATE')
    return


@api_view(['POST'])
@permission_classes([AllowAny])
def account_registration_handler(request):
    if request.method == 'POST':
        serializer = AccountRegistrationSerializer(request.data)
        serializer.is_valid(raise_exception=True)

        email = serializer.validated_data['email']
        password = serializer.validated_data['password']
        invite = serializer.validated_data['invite']

        if is_check_invite_exists(invite):
            if check_invite_not_empty(invite):
                user_id = create_user(email, password, invite)

                return HttpResponse(user_id, 200)
            else:
                return HttpResponse('Invite is empty, give new', 200)
        else:
            return HttpResponse('Invite not exists', 404)

    return HttpResponse('Some error', 500)

accounts/templates/accounts/login.html
{% extends 'index_login.html' %}

{% load static %}
{% load bootstrap4 %}
{% load i18n %}


{% block page_title %}
Login
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% block page_login %}

<div class="container">
    <div class="row">
<div class="login-box center col-md-6 offset-md-3 p-5 my-5">
  <h1 class="login-logo text-center">
    <a href="/"><b>{% trans 'Grand' %}</b></a>{% trans 'Core admin' %}
  </h1>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">{% bootstrap_messages %}</p>

    <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% buttons %}
<!--      <div class="form-group has-feedback">-->
<!--        <input type="email" class="form-control" placeholder="Email">-->
<!--        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>-->
<!--      </div>-->
<!--      <div class="form-group has-feedback">-->
<!--        <input type="password" class="form-control" placeholder="Password">-->
<!--        <span class="glyphicon glyphicon-lock form-control-feedback"></span>-->
<!--      </div>-->
      <div class="row">
<!--        <div class="col-xs-8">-->
<!--          <div class="checkbox icheck">-->
<!--            <label>-->
<!--              <input type="checkbox"> Remember Me-->
<!--            </label>-->
<!--          </div>-->
<!--        </div>-->
        <!-- /.col -->
        <div class="col-xs-4 position-absolute" style="right: 50px;">
          <button type="submit" class="btn btn-primary btn-block btn-flat p-absolute right-0">{% trans 'Sign In' %}</button>
        </div>
        <!-- /.col -->
      </div>
        {% endbuttons %}
    </form>

<!--    <div class="social-auth-links text-center">-->
<!--      <p>- OR -</p>-->
<!--      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using-->
<!--        Facebook</a>-->
<!--      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using-->
<!--        Google+</a>-->
<!--    </div>-->
    <!-- /.social-auth-links -->

<!--    <a href="{#% url 'accounts:restore_password' %#}">I forgot my password</a><br>-->
    <a href="{% url 'accounts:sign_up' %}" class="text-center">{% trans 'Register a new membership' %}</a>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
</div>
</div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'master.html' %}

{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% block page_title %}
{{ user.email }}
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" href="{% static '/accounts/css/style_accounts.css' %}">
{% endblock %}

{% block page_content %}

<!--    <section class="content-header">-->
<!--        <h1>-->
<!--            User Profile-->
<!--        </h1>-->
<!--        <ol class="breadcrumb">-->
<!--            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>-->
<!--&lt;!&ndash;            <li><a href="billhistory/">Bills</a></li>&ndash;&gt;-->
<!--            <li class="active">Profile</li>-->
<!--        </ol>-->
<!--    </section>-->

<section class="container-fluid">

    <div class="row">
        <div class="col-md-3">
            <div class="card card-primary card-outline">
            <div class="card-body box-profile">
                <div class="text-center">
                    <img class="profile-user-img w-35 mx-auto img-responsive img-circle"
                            src="/media/{% firstof user.avatar_thumbnail '/static/img/user-placeholder.svg' %}" alt="User profile picture">
                </div>

                <h3 class="profile-username text-center">{{ user.first_name|default:{% custom_tag _('John') %} }} {{ user.last_name|default:{% custom_tag _('Dou') %} }}</h3>

                <p class="text-muted text-center">{{ user.occupation|default:'' }}</p>

                <ul class="list-group mt-4 list-group-unbordered mb-3">
                  <li class="list-group-item">
                    <b>{% trans 'transFollowers' %}</b> <a class="float-right">1,322</a>
                  </li>
                  <li class="list-group-item">
                    <b>{% trans 'Following' %}</b> <a class="float-right">543</a>
                  </li>
                  <li class="list-group-item">
                    <b>{% trans 'Friends' %}</b> <a class="float-right">13,287</a>
                  </li>
                </ul>

                <a href="#" class="btn btn-primary btn-block"><b>{% trans 'Follow' %}</b></a>
              </div>
            </div>
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title mb-0">{% trans 'About Me' %}</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <strong><i class="fa fa-file-text-o margin-r-5"></i>{% trans 'Обо мне' %}</strong>

                <p class="text-muted">{{ user.about }}</p>
                  <hr>

                <strong><i class="fa fa-map-marker margin-r-5"></i>{% trans 'Location' %}</strong>

                <p class="text-muted">{% trans 'Malibu, California' %}</p>

                <hr>
                  <strong><i class="fa fa-pencil margin-r-5"></i>{% trans 'Ранг' %}</strong>

                    <p>
                        {% for rang in user.rang.all %}
                        <span class="label label-danger">{{ rang.name }}</span>
                        {% endfor %}
                    </p>
                <hr>
                <strong><i class="fa fa-pencil margin-r-5"></i>{% trans 'Скилы' %}</strong>

                <p class="text-muted">
                    {% for skill in user.skills.all %}
                    <span class="badge badge-danger">{{ skill|default:'' }}</span>
                    <!--                  <span class="label label-success"></span>-->
                    <!--                  <span class="label label-info"></span>-->
                    <!--                  <span class="label label-warning"></span>-->
                    <!--                  <span class="label label-primary"></span>-->
                    {% endfor %}
                </p>

                <hr>



                <strong><i class="fa fa-file-text-o margin-r-5"></i>{% trans 'Контакты' %}</strong>

                <p class="text-muted contacts-center">{{ user.phone|default:'' }} {{ user.email|default:'' }} {{ user.telegram|default:'' }}</p>
              </div>
              <!-- /.card-body -->
            </div>
        </div>
        <div class="col-md-9">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active bg-success" href="#settings" data-toggle="tab">{% trans Settings %}</a></li>
                </ul>
              </div><!-- /.card-header -->
                  <div class="tab-pane active" id="settings">
                    <form class="form-vertical px-4 mt-4" method="post" enctype="multipart/form-data">
                      <div class="form-group">
                          {% csrf_token %}
                          {% bootstrap_form form %}
                      </div>
                      <div class="form-group row">
                        <div class="col-sm-12">
                          {% buttons %}
                            <button type="submit" class="btn btn-success">{% trans 'Сохранить' %}</button>
                          {% endbuttons %}
                        </div>
                      </div>
                    </form>
                  </div>
                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
        </div>
    <!-- /.col -->
    </div>
    <!-- /.row -->

</section>

</div>
</div>
</div>
</div>
{% endblock %}

accounts/templates/accounts/resend_activation_code.html
{% extends 'index.html' %}

{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% block page_title %}
Reset password
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% block page_login %}

<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>{% trans 'Product' %}</b>{% trans 'this admin' %}</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">{% trans 'Resend activation code' %}</p>

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form form_group_class='oneOptionFA' %}
<!--      <div class="form-group has-feedback">-->
<!--        <input type="email" class="form-control" placeholder="Email">-->
<!--        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>-->
<!--      </div>-->
<!--      <div class="form-group has-feedback">-->
<!--        <input type="password" class="form-control" placeholder="Password">-->
<!--        <span class="glyphicon glyphicon-lock form-control-feedback"></span>-->
<!--      </div>-->
      <div class="row">
        <div class="col-xs-8">
<!--          <div class="checkbox icheck">-->
<!--            <label>-->
<!--              <input type="checkbox"> Remember Me-->
<!--            </label>-->
<!--          </div>-->
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">{% trans 'Send again' %}</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

<!--    <div class="social-auth-links text-center">-->
<!--      <p>- OR -</p>-->
<!--      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using-->
<!--        Facebook</a>-->
<!--      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using-->
<!--        Google+</a>-->
<!--    </div>-->
    <!-- /.social-auth-links -->

    <a href="{% url 'accounts:login' %}" class="text-center">{% trans 'Login' %}</a>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->


{% endblock %}

accounts/templates/accounts/restore_password.html
{% extends 'index.html' %}

{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% block page_title %}
Reset password
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% block page_login %}

<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>{% trans 'Product' %}</b>{% trans 'this admin' %}</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">{% trans 'Add your email and whee send you new password to email' %}</p>

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form form_group_class='oneOptionFA' %}
<!--      <div class="form-group has-feedback">-->
<!--        <input type="email" class="form-control" placeholder="Email">-->
<!--        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>-->
<!--      </div>-->
<!--      <div class="form-group has-feedback">-->
<!--        <input type="password" class="form-control" placeholder="Password">-->
<!--        <span class="glyphicon glyphicon-lock form-control-feedback"></span>-->
<!--      </div>-->
      <div class="row">
        <div class="col-xs-8">
<!--          <div class="checkbox icheck">-->
<!--            <label>-->
<!--              <input type="checkbox"> Remember Me-->
<!--            </label>-->
<!--          </div>-->
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">{% trans 'Send' %}</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

<!--    <div class="social-auth-links text-center">-->
<!--      <p>- OR -</p>-->
<!--      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using-->
<!--        Facebook</a>-->
<!--      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using-->
<!--        Google+</a>-->
<!--    </div>-->
    <!-- /.social-auth-links -->

    <a href="{% url 'accounts:resend_activation_code' %}">{% trans 'Resend activation code' %}</a><br>
    <a href="{% url 'accounts:login' %}" class="text-center">{% trans 'Login' %}</a>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->


{% endblock %}