accounts/urls.py
from django.urls import path
from .views import MyProfile
from django.contrib.auth import views as auth_views
from .views import (
    LogInView, ResendActivationCodeView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView
)
from django.conf.urls.i18n import i18n_patterns



app_name = 'accounts'


urlpatterns = [
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    #
    # path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),
    #
    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),
    #
    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),
    #
    #
    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
    path('<int:pk>', MyProfile.as_view(), name='myprofile'),
    # path('profileupdate/<int:pk>', MyProfileUpdate.as_view(), name='profileupdate'),
    # path('users/', AllUsersList.as_view(), name='users'),
    # path('create/', CreateUser.as_view(), name='create'),
    # path('delete/<int:pk>', DeleteUser.as_view(), name='delete'),
    # path('detail/<int:pk>', DetailUser.as_view(), name='detail'),
    # path('update/<int:pk>', UserUpdate.as_view(), name='update'),
    # path('mygrouplist/', MyGroupList.as_view(), name='mygrouplist'),
]

api/urls.py
from api.views.accounts import AccountViewSet
from api.views.invites import InviteViewSet, InviteRegistrationViewSet
from api.views.projects import ProjectViewSet

from rest_framework.routers import DefaultRouter
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views.accounts import account_registration_handler

router = DefaultRouter()
router.register('user', AccountViewSet)
router.register('invite', InviteViewSet)
router.register('invite_reg', InviteRegistrationViewSet)
router.register('project', ProjectViewSet)

jwturlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns = [
   path('register_user', account_registration_handler),
] + router.urls  + jwturlpatterns

backend/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import index_page, about_page, home_page, projects_list


from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('accounts/', include("accounts.urls")),
    path('about/', about_page, name="about"),
    path('', home_page, name="home"),
    path('projects/', projects_list, name="projects-list"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

args = tuple(urlpatterns)
urlpatterns = i18n_patterns(*args)

backend/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.utils.translation import ugettext_lazy as _


def index_page(request):
    return render(request, 'index.html', {
        'foo': 'bar',
    }, content_type='text/html')


def about_page(request):
    template = loader.get_template('about.html')
    context = {'text': _('HELLO')}
    return HttpResponse(template.render(context, request))


def home_page(request):
    template = loader.get_template('home.html')
    context = {'go': _('HOME')}
    return HttpResponse(template.render(context, request))


def projects_list(request):
    template = loader.get_template('projects_list.html')
    context = {'project': _('LIFE')}
    return HttpResponse(template.render(context, request))

backend/templates/includes/footer.html
{% load static %}

<footer class="footer">
    <a class="footer__logo" href="/home"></a>
    <nav class="footer-nav">
        <span class="footer-nav__item footer-nav__copy">2019-2020 MIT</span>
        <a class="footer-nav__item item" href="/about">О фонде</a>
        <a class="footer-nav__item item" href="/projects">Проекты</a>
        <a class="footer-nav__item item" href="/community">Участники</a>
        <a class="footer-nav__item item" href="/angels">Спонсоры</a>
        <a class="footer-nav__item item" href="/politics">Политика конфиденциальности</a>
    </nav>
    <div class="footer-socials">
        <a class="footer-socials__item" href="#">
            <img src="{% static '/img/social-icons/vk.svg' %}" alt="vk">
        </a>
        <a class="footer-socials__item" href="#">
            <img src="{% static '/img/social-icons/youtube.svg' %}" alt="youtube">
        </a>
        <a class="footer-socials__item" href="#">
            <img src="{% static '/img/social-icons/telegram.svg' %}" alt="telegram">
        </a>
        <a class="footer-socials__item" href="#">
            <img src="{% static '/img/social-icons/email.svg' %}" alt="email">
        </a>
    </div>
</footer>

backend/templates/includes/header.html
<div class="overlay overlay--hidden"></div>
<div class="header-mobile-nav header-mobile-nav--hidden">
    <div class="header-mobile-nav__close">
        <button class="header-mobile-nav__close-btn btn btn-small" id="close-mobile-nav"></button>
    </div>
    <nav class="header-mobile-nav__nav">
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Софт</b></a>
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Игры</b></a>
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Сервисы</b></a>
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Изделия</b></a>
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Тексты</b></a>
    </nav>
    <nav class="header-mobile-nav__nav">
        <a class="header-mobile-nav__nav-item item" href="/about">О фонде</a>
        <a class="header-mobile-nav__nav-item item" href="/about">Спонсоры</a>
        <a class="header-mobile-nav__nav-item item" href="/about">Участники</a>
    </nav>
    <nav class="header-mobile-nav__nav">
        <a href="{% url 'accounts:login' %}" class="header-mobile-nav__signup-btn btn btn--green">Войти</a>
    </nav>
</div>
<header class="header">
    <div class="header-left-burger" id="burger-btn">
        <label class="burger-toggle">
            <input type="checkbox">
            <div>
                <div>
                    <span></span>
                    <span></span>
                </div>
                <svg>
                    <use xlink:href="#path">
                </svg>
                <svg>
                    <use xlink:href="#path">
                </svg>
            </div>
        </label>
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44 44" id="path">
                <path d="M22,22 L2,22 C2,11 11,2 22,2 C33,2 42,11 42,22"></path>
            </symbol>
        </svg>
    </div>
    <div class="header-left">
        <a class="header-left__logo" href="/home"></a>
        <nav class="header-left__nav nav">
            <a class="header-left__nav-item item" href="/projects">Софт</a>
            <a class="header-left__nav-item item" href="/projects">Игры</a>
            <a class="header-left__nav-item item" href="/projects">Сервисы</a>
            <a class="header-left__nav-item item" href="/projects">Изделия</a>
            <a class="header-left__nav-item item" href="/projects">Тексты</a>
        </nav>
    </div>
    <div class="header-right">
        <nav class="header-right__nav">
            <a class="header-right__nav-item item" href="/about">О фонде</a>
            <a class="header-right__nav-item item" href="/about">Спонсоры</a>
            <a class="header-right__nav-item item" href="/about">Участники</a>
        </nav>
        <div class="header-right-btns">
            <div class="header-right-btns__search">
                <button class="header-right-btns__search-btn header-right-btns__search-btn--action btn btn-small" id="search-btn-action"></button>
                <input type="search" class="header-right-btns__search-field search-field" id="search-field" placeholder="Поиск">
                <button class="header-right-btns__close-btn btn btn-small" id="close-search-field"></button>
            </div>
            <button class="header-right-btns__more-btn btn btn--small" id="show-more"></button>
            <button class="header-right-btns__search-btn btn btn-small" id="search-btn"></button>
            <a href="{% url 'accounts:login' %}" class="header-right-btns__signup-btn btn btn--green">Войти</a>
        </div>
    </div>
</header>

backend/templates/includes/nav.html
    <div class="overlay overlay--hidden"></div>
    <div class="header-mobile-nav header-mobile-nav--hidden">
      <div class="header-mobile-nav__close">
        <button class="header-mobile-nav__close-btn btn btn-small" id="close-mobile-nav"></button>
      </div>
      <nav class="header-mobile-nav__nav">
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Софт</b></a>
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Игры</b></a>
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Cервисы</b></a>
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Изделия</b></a>
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Тексты</b></a>
      </nav>
      <nav class="header-mobile-nav__nav">
        <a class="header-mobile-nav__nav-item item" href="/about">О фонде</a>
        <a class="header-mobile-nav__nav-item item" href="/angels">Спонсоры</a>
        <a class="header-mobile-nav__nav-item item" href="/community">Участники</a>
      </nav>
      <nav class="header-mobile-nav__nav">
        <a href="{% url 'accounts:login' %}" class="header-mobile-nav__signup-btn btn btn--green">Войти</a>
      </nav>
    </div>